apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must be in the form: <plural>.<group>
  name: testpods.test.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: test.com
  scope: Namespaced
  names:
    # kind is normally the CamelCased singular type. 
    kind: TestPod
    # singular name to be used as an alias on the CLI
    singular: testpod
    # plural name in the URL: /apis/<group>/<version>/<plural>
    plural: testpods
    shortNames:
      - tp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            name:
              type: string
            metadata:
              type: object
              properties:
                name:
                  type: string
            custom_annotations:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  value:
                    type: string
            image_name:
              type: string
            image_url:
              type: string
            image_tag:
              type: string
            secrets:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
            args:
              type: array
              items:
                type: string
            command:
              type: array
              items:
                type: string
            restartPolicy:
              type: string



                     
